<?xml version="1.0"?>
<robot name="mecanum" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:include filename="$(find nav)/urdf/omniurdf/robot_omni.gazebo" />
  <xacro:include filename="$(find nav)/urdf/omniurdf/materials.xacro" />
  <xacro:include filename="$(find nav)/urdf/omniurdf/inertial.xacro" />
  <xacro:include filename="$(find nav)/urdf/omniurdf/range.xacro" />

  <xacro:property name="base_width" value="0.3683" />
  <xacro:property name="base_length" value="0.3683" />
  <xacro:property name="base_height" value="0.0635" />
  <xacro:property name="wheel_radius" value="0.1016" />
  <xacro:property name="wheel_width" value="0.0762" />
  <xacro:property name="wheel_gap" value="0.0508" />
  <xacro:property name="wheel_setback" value="0.041275" />
  <xacro:property name="lidar_width" value="0.0508" />
  <xacro:property name="lidar_length" value="0.0508" />
  <xacro:property name="lidar_height" value="0.0762" />
  <xacro:property name="lidar_setback" value="0.0127" />


  <!--~~~~~~~~~~~~~~~~~~~~~~~~ ~ ROBOT BASE ~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->

  <link name="base_link">
    <collision>
      <origin xyz="0 0 0.0" rpy="0 0 0"/>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0.0" rpy="0 0 0"/>
      <geometry>
	       <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial>
      <mass value="3.1" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="1e-1" ixy="0" ixz="0" iyy="1e-1" iyz="0" izz="1e-1" />
    </inertial>
  </link>

  <link name="fl_link">
      <visual>
        <origin xyz="0 0 0" rpy="${pi/2} 0.0 0.0"/>
        <geometry>
          <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
          <!-- <mesh filename="package://nav/urdf/omniurdf/Left_wheel.stl" scale="0.0015 0.0015 0.0015"/> -->
        </geometry>
        <material name="white"/>
      </visual>

      <collision>
        <geometry>
          <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
        </geometry>
        <origin rpy="${pi/2} 0 0" xyz="0 0 0"/>
      </collision>

      <inertial>
        <mass value="0.01" />
        <origin rpy="${pi/2} 0 0" xyz="0 0 0"/>
        <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
      </inertial>
    </link>

    <link name="fr_link">
        <visual>
          <origin rpy="${pi/2} 0 0" xyz="0 0 0"/>
          <geometry>
            <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
            <!-- <mesh filename="package://nav/urdf/omniurdf/Right_wheel.stl" scale="0.0015 0.0015 0.0015"/> -->
          </geometry>
          <material name="white"/>
        </visual>

        <collision>
          <geometry>
            <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
          </geometry>
          <origin rpy="${pi/2} 0 0" xyz="0 0 0"/>
        </collision>

        <inertial>
          <mass value="0.01" />
          <origin rpy="${pi/2} 0 0" xyz="0 0 0"/>
          <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
        </inertial>
      </link>
      <link name="bl_link">
          <visual>
            <geometry>
            <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
              <!-- <mesh filename="package://nav/urdf/omniurdf/Right_wheel.stl" scale="0.0015 0.0015 0.0015"/> -->
            </geometry>
            <origin rpy="${pi/2} 0 0" xyz="0 0 0"/>
            <material name="white"/>
          </visual>

          <collision>
            <geometry>
              <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
            </geometry>
            <origin rpy="${pi/2} 0 0" xyz="0 0 0"/>
          </collision>

          <inertial>
            <mass value="0.01" />
            <origin rpy="${pi/2} 0 0" xyz="0 0 0"/>
            <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
          </inertial>
        </link>

        <link name="br_link">
            <visual>
            <origin rpy="${pi/2} 0 0" xyz="0 0 0"/>
              <geometry>
                <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
                <!-- <mesh filename="package://nav/urdf/omniurdf/Left_wheel.stl" scale="0.0015 0.0015 0.0015"/> -->
              </geometry>
              <material name="white"/>
            </visual>
            <collision>
              <geometry>
                <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
              </geometry>
              <origin rpy="${pi/2} 0 0" xyz="0 0 0"/>
            </collision>

            <inertial>
              <mass value="0.01" />
              <origin rpy="${pi/2} 0 0" xyz="0 0 0"/>
              <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
            </inertial>
          </link>

    <!-- ROBOT TOOLS -->
    <!-- <link name="claw_link">

      <collision>
        <origin xyz="0 0 0.0" rpy="0 0 0"/>
        <geometry>
          <box size="0.1 ${base_width + 0.23} ${base_height*3.3}"/>
        </geometry>
      </collision>

      <visual>
        <origin xyz="0 0.05 -0.34" rpy="0 0 ${-pi/2}"/>
        <geometry>
                                                            <box size="0.03 ${base_width + 0.23} ${base_height*2}"/>
          <mesh filename="package://nav/urdf/omniurdf/claw.stl" scale="0.15 0.1 0.07"/>
        </geometry>
        <material name="orange"/>
      </visual>

      <inertial>
        <mass value="0.1" />
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <inertia ixx="1e-3" ixy="0" ixz="0" iyy="1e-3" iyz="0" izz="1e-3" />
      </inertial>
    </link>

    <joint type="fixed" name="claw_joint">
      <origin xyz="${base_length/2 + 0.15} 0 0" rpy="0 0 0"/>
      <child link="claw_link"/>
      <parent link="base_link"/>
    </joint> -->


  <!--~~~~~~~~~~~~~~~~~~~~~~~ ~ Sensors ~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->

  <link name='camera'>
    <visual name='camera_visual'>
      <origin xyz="0 0 -0.05" rpy=" 0 0 0"/>
      <geometry>
        <box size=".03 .05 .10"/>
      </geometry>
      <material name="black"/>
    </visual>
  </link>

  <joint type="fixed" name="camera_joint">
    <origin xyz="0 0 0.1" rpy="0 0 0"/>
    <child link="camera"/>
    <parent link="base_link"/>
  </joint>


<xacro:range side="front" x="${base_length/2}" y="0" z="${base_height/2}" roll="0" pitch="0" yaw="0"/>
<xacro:range side="rear" x="${-base_length/2}" y="0" z="${base_height/2}" roll="0" pitch="0" yaw="${pi}"/>
<xacro:range side="left" x="0" y="${base_width/2}" z="${base_height/2}" roll="0" pitch="0" yaw="${pi/2}"/>
<xacro:range side="right" x="0" y="${-base_width/2}" z="${base_height/2}" roll="0" pitch="0" yaw="${-pi/2}"/>

  <!--~~~~~~~~~~~~~~~~~~~~~~~ ~ /Sensors ~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->

  <joint name="fl_joint" type="continuous">
      <parent link="base_link"/>
      <child link="fl_link"/>
      <origin rpy="0 0 0" xyz="${base_length/2 - wheel_setback} ${base_width/2 + wheel_gap} 0.0"/>
      <axis xyz="0 1 0"/>
      <dynamics damping="1.0" friction="0.2" spring_stiffness="1" />
      <limit effort="50" velocity="0.7" />
  </joint>
  <transmission name="fl_joint_trans">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="fl_joint">
      <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
    </joint>
    <actuator name="fl_joint_wheel_motor">
      <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <joint name="fr_joint" type="continuous">
      <parent link="base_link"/>
      <child link="fr_link"/>
      <origin rpy="0 0 0" xyz="${base_length/2 - wheel_setback} ${-base_width/2 - wheel_gap} 0.0"/>
      <axis xyz="0 1 0"/>
      <dynamics damping="1.0" friction="0.2" spring_stiffness="1" />
      <limit effort="50" velocity="0.7" />
  </joint>
  <transmission name="fr_joint_trans">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="fr_joint">
      <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
    </joint>
    <actuator name="fr_joint_wheel_motor">
      <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <joint name="bl_joint" type="continuous">
      <parent link="base_link"/>
      <child link="bl_link"/>
      <origin rpy="0 0 0" xyz="${-base_length/2 + wheel_setback} ${base_width/2 + wheel_gap} 0.0"/>
      <axis xyz="0 1 0"/>
      <dynamics damping="1.0" friction="0.2" spring_stiffness="1" />
      <limit effort="50" velocity="0.7"/>
  </joint>
    <transmission name="bl_joint_trans">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="bl_joint">
      <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
    </joint>
    <actuator name="bl_joint_wheel_motor">
      <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <joint name="br_joint" type="continuous">
      <parent link="base_link"/>
      <child link="br_link"/>
      <origin rpy="0 0 0" xyz="${-base_length/2 + wheel_setback} ${-base_width/2 - wheel_gap} 0.0"/>
      <axis xyz="0 1 0"/>
      <dynamics damping="1.0" friction="0.2" spring_stiffness="1" />
      <limit effort="50" velocity="0.7" />
  </joint>
  <transmission name="br_joint_trans">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="br_joint">
      <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
    </joint>
    <actuator name="br_joint_wheel_motor">
      <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>


</robot>
