services:
  ros_sim_pc:
    image: ilya9kkk/ros_itmo:base
    container_name: ros_sim_pc
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - XAUTHORITY=${XAUTHORITY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /dev:/dev
      - "../workspace:/workspace"
      - "./:/workspace/pc_sim_run"  # Монтируем текущую директорию в контейнер
    network_mode: "host"  # Используем сетевой режим хоста
    privileged: true  # Требуется для работы с устройствами
    stdin_open: true  # Для запуска контейнера в интерактивном режиме
    tty: true  # Ожидание ввода
    entrypoint: ["/bin/bash", "-c", "/workspace/pc_sim_run/pc_sim_start.bash"]