// Generated by gencpp from file my_super_robot_controller/my_Num.msg
// DO NOT EDIT!


#ifndef MY_SUPER_ROBOT_CONTROLLER_MESSAGE_MY_NUM_H
#define MY_SUPER_ROBOT_CONTROLLER_MESSAGE_MY_NUM_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace my_super_robot_controller
{
template <class ContainerAllocator>
struct my_Num_
{
  typedef my_Num_<ContainerAllocator> Type;

  my_Num_()
    : x(0)
    , y(0)  {
    }
  my_Num_(const ContainerAllocator& _alloc)
    : x(0)
    , y(0)  {
  (void)_alloc;
    }



   typedef uint32_t _x_type;
  _x_type x;

   typedef uint32_t _y_type;
  _y_type y;





  typedef boost::shared_ptr< ::my_super_robot_controller::my_Num_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_super_robot_controller::my_Num_<ContainerAllocator> const> ConstPtr;

}; // struct my_Num_

typedef ::my_super_robot_controller::my_Num_<std::allocator<void> > my_Num;

typedef boost::shared_ptr< ::my_super_robot_controller::my_Num > my_NumPtr;
typedef boost::shared_ptr< ::my_super_robot_controller::my_Num const> my_NumConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_super_robot_controller::my_Num_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_super_robot_controller::my_Num_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::my_super_robot_controller::my_Num_<ContainerAllocator1> & lhs, const ::my_super_robot_controller::my_Num_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::my_super_robot_controller::my_Num_<ContainerAllocator1> & lhs, const ::my_super_robot_controller::my_Num_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace my_super_robot_controller

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::my_super_robot_controller::my_Num_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_super_robot_controller::my_Num_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_super_robot_controller::my_Num_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_super_robot_controller::my_Num_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_super_robot_controller::my_Num_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_super_robot_controller::my_Num_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_super_robot_controller::my_Num_<ContainerAllocator> >
{
  static const char* value()
  {
    return "64be90712af6ea79ae6f103da824ffcf";
  }

  static const char* value(const ::my_super_robot_controller::my_Num_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x64be90712af6ea79ULL;
  static const uint64_t static_value2 = 0xae6f103da824ffcfULL;
};

template<class ContainerAllocator>
struct DataType< ::my_super_robot_controller::my_Num_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_super_robot_controller/my_Num";
  }

  static const char* value(const ::my_super_robot_controller::my_Num_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_super_robot_controller::my_Num_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 x\n"
"uint32 y\n"
;
  }

  static const char* value(const ::my_super_robot_controller::my_Num_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_super_robot_controller::my_Num_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct my_Num_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_super_robot_controller::my_Num_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_super_robot_controller::my_Num_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_SUPER_ROBOT_CONTROLLER_MESSAGE_MY_NUM_H
