omni_control:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
  front_right_wheel_joint:
    type: velocity_controllers/JointVelocityController
    joint: fr_joint
    pid: {p: 2.4, i: 0.0, d: 0.0}
  front_left_wheel_joint:
    type: velocity_controllers/JointVelocityController
    joint: fl_joint
    pid: {p: 2.4, i: 0.0, d: 0.0}
  back_left_wheel_joint:
    type: velocity_controllers/JointVelocityController
    joint: br_joint
    pid: {p: 2.4, i: 0.0, d: 0.0}
  back_right_wheel_joint:
    type: velocity_controllers/JointVelocityController
    joint: bl_joint
    pid: {p: 2.4, i: 0.0, d: 0.0}