omni_control:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
  fl_joint:
    type: velocity_controllers/JointVelocityController
    joint: fl_joint
    pid: {p: 2.4, i: 0.0, d: 0.0}
  fr_joint:
    type: velocity_controllers/JointVelocityController
    joint: fr_joint
    pid: {p: 2.4, i: 0.0, d: 0.0}
  bl_joint:
    type: velocity_controllers/JointVelocityController
    joint: bl_joint
    pid: {p: 2.4, i: 0.0, d: 0.0}
  br_joint:
    type: velocity_controllers/JointVelocityController
    joint: br_joint
    pid: {p: 2.4, i: 0.0, d: 0.0}
  gazebo_ros_control:
    pid_gains:
      fl_joint: {p: 1.0, i: 0.0, d: 0.0}
      fr_joint: {p: 1.0, i: 0.0, d: 0.0}
      bl_joint: {p: 1.0, i: 0.0, d: 0.0}
      br_joint: {p: 1.0, i: 0.0, d: 0.0}